version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: qiitadeck
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
    restart: on-failure

  nest:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:80
    command: [sh, entrypoint.sh]
    env_file:
      - docker-compose.env
    volumes:
      - .:/app
    links:
      - db
    restart: on-failure